### ISSUE TITLE
 train into one moel or train one by one?

### ISSUE THREAD

**Issue by Deicide-LC** [solawen/FashionAI_KeyPoint_Detection_Challenge#3]
thanks for sharing , I want to know if  this code could put different categories of clothes  into one model? If it works ,how can I make it? I am looking forward to your reply ,thank you very much

**Comment by solawen** [comment]
It will train one model for all categories. The model will output 24 heatmaps which contains the  keypoins that all the categories have. Of course, only a part of heatmaps are useful for a particular category.

**Comment by Deicide-LC** [comment]
@solawen Got it ,Thanks for your reply!
